config/routes.rb
Rails.application.routes.draw do
  get 'customers/index'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "customers#index", as: 'root'
  
  get 'customers/missing_email', to: 'customers#missing_email', as: 'missing_email'

  get 'customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized'

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :full_name, presence: true
    belongs_to :province
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :customers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @ordered_customers = Customer.all.order(:full_name)
  end

  def missing_email
    @missing_email_customers = Customer.where(:email_address => "")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/common/_menu.html.erb
<header>
    <nav>
      <ul>
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Alphabetized', alphabetized_path %></li>
         <li><%= link_to 'Missing Email', missing_email_path %></li>
      </ul>
    </nav> 
  </header>

app/views/customers/_customer.html.erb
<div class ="customer">
    <h4><%= customer.full_name %></h4>

    <% if customer.image.present? %>
        <%= image_tag customer.image %>
    <%end%>
        
    <p>
        <strong>Province:</strong>
        <% if customer.province.present? %>
            <%= customer.province.name %>
        <% else %>
            None
        <% end %>

    <p>

    <p>
       <%= customer.phone_number %>
    </p>

    <p>
       <%= customer.email_address %>
    </p>
</div>

app/views/customers/alphabetized.html.erb
<h1>Aplhabetized Customers</h1>
<%= render partial: 'common/menu'%>
<%= render @ordered_customers %>

app/views/customers/index.html.erb
<h1>All Customers</h1>
<%= render partial: 'common/menu'%>
<%= render @customers %>

app/views/customers/missing_email.html.erb
<h1> Missing Email Customers</h1>
<%= render partial: 'common/menu'%>
<%= render @missing_email_customers %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRMChallenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>